services:
  mysql-concurrency:
    image: mysql:8.0
    container_name: dbms-mysql-concurrency
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_registration
    ports:
      - "3308:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --transaction-isolation=REPEATABLE-READ
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  mongodb-concurrency:
    image: mongo:7
    container_name: dbms-mongo-concurrency
    environment:
      MONGO_INITDB_DATABASE: course_registration
    ports:
      - "27019:27017"
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      retries: 10
      interval: 10s

networks:
  default:
    name: concurrency-network
